{% set version = "2.0.0" %}

package:
  name: mne-kit-gui
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mne-kit-gui/mne_kit_gui-{{ version }}.tar.gz
  sha256: ed196147ebea3a331565d8be3ef918392bbb2f58c3026af1f03367cd220a129f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=64
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.11
    - numpy
    - pyvista >=0.43
    - pyvistaqt
    - traitlets
    - qtpy
    - mne-base >=1.6

test:
  imports:
    - mne_kit_gui
  commands:
    - pip check
  requires:
    - pip
    - python
    - pyside6

about:
  home: https://github.com/mne-tools/mne-kit-gui
  summary: A module for KIT MEG coregistration.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
